// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rjswcizqvjdinuymdqgw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqc3djaXpxdmpkaW51eW1kcWd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5NjEzNTksImV4cCI6MjA2MDUzNzM1OX0.oDA5d1ji1CzFYnR7bG7-R7JmmF1B0v7Ef7Dwemno7sU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);